services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: sapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - default

  api:
    image: juzaetum/ac2_devops_alunoserecompensas:latest
    depends_on:
      - database
    ports:
      - "8686:8080"
    environment:
      SPRING_PROFILES_ACTIVE: stage
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: sapi
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - default

volumes:
  db-volume:

networks:
  default:
    driver: bridge
